# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: somegroup

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo a=$(a)
    echo b=$(b)
    echo c=$(c)
    echo contososecret=$CONTOSO_SECRET
    echo contososecret=$env:CONTOSO_SECRET
    echo contososecret=env:$CONTOSO_SECRET
    echo is a less than b? ${{ lt(variables.a, variables.b) }}
    echo is a equal to b? ${{ eq(variables.a, variables.b) }}
    echo is a greater than b? ${{ gt(variables.a, variables.b) }}
  displayName: 'Run one multi-line script'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    CONTOSO_SECRET: $(contososecret)
