# parameters:
# - name: image
#   displayName: 'Pool image'
#   default: ubuntu-latest
#   values:
#   - windows-latest
#   - vs2017-win2016
#   - ubuntu-latest
#   - ubuntu-16.04
#   - macOS-latest
#   - macOS-10.14
# - name: test
#   displayName: Run Tests?
#   type: boolean
#   default: false

variables:
- group: "Contoso Variable Group"
- name: va
  value: $[variables.a]
- name: vb
  value: $[variables.b]
- name: vcontososecret
  value: $[variables.contososecret]

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Hello, world!
    echo Pool image: ${{ parameters.image }}
    echo Run tests? ${{ parameters.test }}
  displayName: 'Show runtime parameter values'

- script: |
    echo a=$(va)
    echo b=$(vb)
    echo contososecret=$(vcontososecret)
    echo Is a less than b? ${{ lt(variables.va, variables.vb) }}
    echo Is a equal to b? ${{ eq(variables.va, variables.vb) }}
    echo Is a greater than b? ${{ gt(variables.va, variables.vb) }}
    echo Is a greater than contososecret? ${{ gt(variables.va, variables.vcontososecret) }}
    echo Is b greater than contososecret? ${{ gt(variables.vb, variables.vcontososecret) }}
    echo Is a less than contososecret? ${{ lt(variables.va, variables.vcontososecret) }}
    echo Is b less than contososecret? ${{ lt(variables.vb, variables.vcontososecret) }}
    echo
    for number in {1..$(contososecret)}
    do
      echo $number
    done
  displayName: 'Test variable group variables (secret and nonsecret)'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)