# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: image
  displayName: Pool Image
  #default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14
- name: test
  displayName: Run Tests?
  type: boolean
  #default: false

variables:
- group: somegroup
- name: va
  value: $[variables.a]
- name: vb
  value: $[variables.b]
- name: vc
  value: $[variables.c]
- name: vcontososecret
  value: $[variables.contososecret]

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo Pool image: ${{ parameters.image }}
    echo Run tests? ${{ parameters.test }}
    echo a=$(va)
    echo b=$(vb)
    echo c=$(vc)
    echo contososecret=$(vcontososecret)
    echo Is a less than b? ${{ lt(variables.va, variables.vb) }}
    echo Is a equal to b? ${{ eq(variables.va, variables.vb) }}
    echo Is a greater than b? ${{ gt(variables.va, variables.vb) }}
    echo Is a less than contososecret? ${{ lt(variables.va, variables.vcontososecret) }}
    echo Is b less than contososecret? ${{ lt(variables.vb, variables.vcontososecret) }}
    echo Is c less than contososecret? ${{ lt(variables.vc, variables.vcontososecret) }}
  displayName: 'Run one multi-line script'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
