# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: somegroup
- name: va
  value: $[variables.a]
- name: vb
  value: $[variables.b]
- name: vc
  value: $[variables.c]

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo a=$(va)
    echo b=$(vb)
    echo c=$(vc)
    echo contososecret=$CONTOSO_SECRET
    echo contososecret=$env:CONTOSO_SECRET
    echo contososecret=env:$CONTOSO_SECRET
    echo Is a less than b? ${{ lt(variables.va, variables.vb) }}
    echo Is a equal to b? ${{ eq(variables.va, variables.vb) }}
    echo Is a greater than b? ${{ gt(variables.va, variables.vb) }}
  displayName: 'Run one multi-line script'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    CONTOSO_SECRET: $(contososecret)
