# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: somegroup

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo a=$(a)
    echo b=$(b)
    echo c=$(c)
    echo contososecret=$CONTOSO_SECRET
    echo is a less than contososecret? $[lt($(a), $CONTOSO_SECRET)]
    echo is b less than contososecret? $[lt($(b), $CONTOSO_SECRET)]
    echo is c less than contososecret? $[lt($(c), $CONTOSO_SECRET)]
  displayName: 'Run a multi-line script'
  env:
    CONTOSO_SECRET: $(contososecret)
